# Generated by Django 3.0.7 on 2020-06-12 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
